turtlesim_image_painter:
  ros__parameters:
    max_width: 64
    max_height: 64
    palette_size: 8
    transparency_color: [255, 255, 255]
    background_threshold: 0.5
    allow_upscale: false
    canvas_min_x: 1.0
    canvas_max_x: 10.0
    canvas_min_y: 1.0
    canvas_max_y: 10.0
    exclude_background: true
